kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ops-mgmt
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true,topology.kubernetes.io/zone=cn-shenzhen-a"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30300
        hostPort: 30300
        protocol: TCP
      - containerPort: 32409
        hostPort: 32409
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
  - role: worker
  - role: worker
