kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: biz-prod-regionb
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "topology.kubernetes.io/region=cn-south,topology.kubernetes.io/zone=cn-shenzhen-b"
  - role: worker
  - role: worker
